-- =====================================================================
-- DelhiDrive — refresh fleet + coupons to the live NCR Drive catalogue
-- =====================================================================
-- Run this in Supabase: SQL Editor -> New query -> paste -> Run.
--
-- Replaces the 14 placeholder demo cars with the real 23-vehicle fleet
-- (actual names, photos and 6h/12h/24h prices). Existing bookings are
-- untouched. Safe to run more than once.
-- =====================================================================

-- Remove the old placeholder cars (their ids all began with these stems).
delete from public.fleet
where id like 'dd-swift-%'  or id like 'dd-i20-%'    or id like 'dd-tiago-%'
   or id like 'dd-city-%'   or id like 'dd-verna-%'  or id like 'dd-slavia-%'
   or id like 'dd-creta-0%' or id like 'dd-nexon-%'  or id like 'dd-scorpio-0%'
   or id like 'dd-xuv700-%' or id like 'dd-thar-1%'  or id like 'dd-c200-%'
   or id like 'dd-bmw3-%'   or id like 'dd-fortuner-%';

-- Upsert the real fleet. Re-running refreshes prices without duplicating.
insert into public.fleet (id, data) values
  ('dd-maruti-suzuki-celerio', '{"name":"Maruti Suzuki Celerio","brand":"Maruti Suzuki","category":"Hatchback","transmission":"Manual","fuel":"Petrol","seats":5,"mileage":26.7,"rate":1499,"rate6h":600,"rate12h":900,"extraKmCharge":10,"engineCc":998,"bootLitres":313,"deposit":3000,"plate":"DL 1C AB 1000","hub":"cp","colorHex":"#c0392b","terrain":["City"],"zeroDep":false,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/maruti-suzuki-celerio.jpg","features":["AMT-smooth city drive","Compact and easy to park","Bluetooth audio","Best-in-class mileage"],"reviews":[]}'::jsonb),
  ('dd-maruti-suzuki-wagonr', '{"name":"Maruti suzuki WagonR","brand":"Maruti Suzuki","category":"Hatchback","transmission":"Manual","fuel":"Petrol","seats":5,"mileage":25.2,"rate":1499,"rate6h":600,"rate12h":900,"extraKmCharge":10,"engineCc":998,"bootLitres":341,"deposit":3000,"plate":"DL 2C BE 1137","hub":"t3","colorHex":"#2980b9","terrain":["City"],"zeroDep":false,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/maruti-suzuki-wagonr.jpg","features":["Tall-boy cabin, easy entry","Great visibility in traffic","Bluetooth audio","Very low running cost"],"reviews":[]}'::jsonb),
  ('dd-maruti-suzuki-swift', '{"name":"Maruti Suzuki Swift","brand":"Maruti Suzuki","category":"Hatchback","transmission":"Manual","fuel":"Petrol","seats":5,"mileage":22.4,"rate":1699,"rate6h":680,"rate12h":1020,"extraKmCharge":10,"engineCc":1197,"bootLitres":265,"deposit":3000,"plate":"DL 3C CH 1274","hub":"cyber","colorHex":"#c0392b","terrain":["City","Highway"],"zeroDep":false,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/maruti-suzuki-swift.jpg","features":["Peppy 1.2 petrol","Touchscreen + Android Auto","Rear parking sensors","Fun to drive"],"reviews":[]}'::jsonb),
  ('dd-hyundai-aura', '{"name":"Hyundai Aura","brand":"Hyundai","category":"Sedan","transmission":"Manual","fuel":"Petrol","seats":5,"mileage":20.5,"rate":1897,"rate6h":760,"rate12h":1140,"extraKmCharge":10,"engineCc":1197,"bootLitres":402,"deposit":3000,"plate":"DL 4C DK 1411","hub":"noida18","colorHex":"#ecf0f1","terrain":["City","Highway"],"zeroDep":false,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/hyundai-aura.jpg","features":["402 L boot","Wireless charging","Rear AC vents","Cruise control"],"reviews":[]}'::jsonb),
  ('dd-toyota-glanza', '{"name":"Toyota Glanza","brand":"Toyota","category":"Hatchback","transmission":"Manual","fuel":"Petrol","seats":5,"mileage":22.9,"rate":1899,"rate6h":760,"rate12h":1140,"extraKmCharge":10,"engineCc":1197,"bootLitres":318,"deposit":3000,"plate":"DL 5C EN 1548","hub":"cp","colorHex":"#34495e","terrain":["City","Highway"],"zeroDep":false,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/toyota-glanza.jpg","features":["Toyota reliability","Touchscreen + Android Auto","Rear camera","Excellent mileage"],"reviews":[]}'::jsonb),
  ('dd-maruti-suzuki-baleno', '{"name":"Maruti Suzuki Baleno","brand":"Maruti Suzuki","category":"Hatchback","transmission":"Manual","fuel":"Petrol","seats":5,"mileage":22.3,"rate":1899,"rate6h":760,"rate12h":1140,"extraKmCharge":10,"engineCc":1197,"bootLitres":318,"deposit":3000,"plate":"DL 6C FQ 1685","hub":"t3","colorHex":"#2c3e50","terrain":["City","Highway"],"zeroDep":false,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/maruti-suzuki-baleno.jpg","features":["Roomy cabin","HeadUp display","360 camera","6 airbags"],"reviews":[]}'::jsonb),
  ('dd-honda-amaze', '{"name":"Honda Amaze","brand":"Honda","category":"Sedan","transmission":"Manual","fuel":"Diesel","seats":5,"mileage":24.7,"rate":1999,"rate6h":800,"rate12h":1200,"extraKmCharge":10,"engineCc":1498,"bootLitres":420,"deposit":3000,"plate":"DL 7C GT 1822","hub":"cyber","colorHex":"#7f8c8d","terrain":["City","Highway"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/honda-amaze.jpg","features":["Diesel torque","420 L boot","Cruise control","Superb highway economy"],"reviews":[]}'::jsonb),
  ('dd-tata-punch', '{"name":"Tata Punch","brand":"Tata Motors","category":"Hatchback","transmission":"Manual","fuel":"Petrol","seats":5,"mileage":20.1,"rate":1999,"rate6h":800,"rate12h":1200,"extraKmCharge":10,"engineCc":1199,"bootLitres":366,"deposit":3000,"plate":"DL 8C HW 1959","hub":"noida18","colorHex":"#d35400","terrain":["City"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/tata-punch.jpg","features":["5-star GNCAP safety","High ground clearance","Touchscreen","SUV stance"],"reviews":[]}'::jsonb),
  ('dd-maruti-suzuki-dzire', '{"name":"Maruti Suzuki Dzire","brand":"Maruti Suzuki","category":"Sedan","transmission":"Manual","fuel":"Petrol","seats":5,"mileage":24.1,"rate":1999,"rate6h":800,"rate12h":1200,"extraKmCharge":10,"engineCc":1197,"bootLitres":378,"deposit":3000,"plate":"DL 9C IZ 2096","hub":"cp","colorHex":"#ecf0f1","terrain":["City","Highway"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/maruti-suzuki-dzire.jpg","features":["Roomy rear seat","378 L boot","Rear AC vents","Very economical"],"reviews":[]}'::jsonb),
  ('dd-tata-punch-facelift-2026', '{"name":"Tata punch Facelift 2026","brand":"Tata Motors","category":"Hatchback","transmission":"Automatic","fuel":"CNG","seats":5,"mileage":26.9,"rate":2199,"rate6h":880,"rate12h":1320,"extraKmCharge":10,"engineCc":1199,"bootLitres":210,"deposit":4000,"plate":"DL 1C JD 2233","hub":"t3","colorHex":"#16a085","terrain":["City"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/tata-punch-facelift-2026.jpg","features":["CNG - lowest running cost","Automatic gearbox","5-star safety","2026 facelift"],"reviews":[]}'::jsonb),
  ('dd-maruti-suzuki-fronx', '{"name":"Maruti Suzuki Fronx","brand":"Maruti Suzuki","category":"SUV","transmission":"Manual","fuel":"Petrol","seats":5,"mileage":21.8,"rate":2199,"rate6h":880,"rate12h":1320,"extraKmCharge":10,"engineCc":1197,"bootLitres":308,"deposit":4000,"plate":"DL 2C KG 2370","hub":"cyber","colorHex":"#2980b9","terrain":["City","Highway"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/maruti-suzuki-fronx.jpg","features":["Coupe-SUV styling","360 camera","HeadUp display","Wireless CarPlay"],"reviews":[]}'::jsonb),
  ('dd-hyundai-venue-s', '{"name":"Hyundai venue S+","brand":"Hyundai","category":"SUV","transmission":"Manual","fuel":"Petrol","seats":5,"mileage":17.5,"rate":2280,"rate6h":920,"rate12h":1370,"extraKmCharge":8,"engineCc":1197,"bootLitres":350,"deposit":4000,"plate":"DL 3C LJ 2507","hub":"noida18","colorHex":"#34495e","terrain":["City","Highway"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/hyundai-venue-s.png","features":["Sunroof","Wireless charging","Rear camera","Connected car tech"],"reviews":[]}'::jsonb),
  ('dd-maruti-suzuki-ciaz-zxi', '{"name":"Maruti Suzuki Ciaz Zxi","brand":"Maruti Suzuki","category":"Hatchback","transmission":"Manual","fuel":"Petrol","seats":5,"mileage":20.6,"rate":2349,"rate6h":940,"rate12h":1410,"extraKmCharge":8,"engineCc":1462,"bootLitres":510,"deposit":4000,"plate":"DL 4C MM 2644","hub":"cp","colorHex":"#ecf0f1","terrain":["City","Highway"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/maruti-suzuki-ciaz-zxi.jpg","features":["510 L boot - huge","Limousine-like rear space","Cruise control","Very comfortable"],"reviews":[]}'::jsonb),
  ('dd-mahindra-xuv-300', '{"name":"Mahindra Xuv 300","brand":"Mahindra","category":"SUV","transmission":"Manual","fuel":"Petrol","seats":5,"mileage":17,"rate":2399,"rate6h":960,"rate12h":1440,"extraKmCharge":10,"engineCc":1197,"bootLitres":257,"deposit":4000,"plate":"DL 5C NP 2781","hub":"t3","colorHex":"#c0392b","terrain":["City","Highway"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/mahindra-xuv-300.jpg","features":["5-star GNCAP safety","7 airbags","Sunroof","Best-in-class braking"],"reviews":[]}'::jsonb),
  ('dd-hyundai-venue', '{"name":"Hyundai Venue","brand":"Hyundai","category":"SUV","transmission":"Manual","fuel":"Petrol","seats":5,"mileage":17.5,"rate":2399,"rate6h":960,"rate12h":1440,"extraKmCharge":10,"engineCc":1197,"bootLitres":350,"deposit":4000,"plate":"DL 6C OS 2918","hub":"cyber","colorHex":"#2c3e50","terrain":["City","Highway"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/hyundai-venue.jpg","features":["Compact SUV","Touchscreen","Rear camera","Easy in city traffic"],"reviews":[]}'::jsonb),
  ('dd-maruti-suzuki-breeza', '{"name":"Maruti Suzuki breeza","brand":"Maruti Suzuki","category":"SUV","transmission":"Manual","fuel":"Petrol","seats":5,"mileage":17.4,"rate":2399,"rate6h":960,"rate12h":1440,"extraKmCharge":10,"engineCc":1462,"bootLitres":328,"deposit":4000,"plate":"DL 7C PV 3055","hub":"noida18","colorHex":"#ecf0f1","terrain":["City","Highway"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/maruti-suzuki-breeza.jpg","features":["Sunroof","360 camera","6 airbags","Proven reliability"],"reviews":[]}'::jsonb),
  ('dd-mahindra-xuv500', '{"name":"Mahindra Xuv500","brand":"Mahindra","category":"SUV","transmission":"Manual","fuel":"Diesel","seats":7,"mileage":15.1,"rate":2799,"rate6h":1120,"rate12h":1680,"extraKmCharge":12,"engineCc":2179,"bootLitres":93,"deposit":4000,"plate":"DL 8C QY 3192","hub":"cp","colorHex":"#2c3e50","terrain":["Highway","Hills"],"zeroDep":true,"available":false,"status":"maintenance","rating":4.5,"reviewCount":0,"photo":"cars/mahindra-xuv500.jpg","features":["7 seats","Diesel torque","Sunroof","Commanding driving position"],"reviews":[]}'::jsonb),
  ('dd-mahindra-scorpio-classic', '{"name":"Mahindra Scorpio Classic","brand":"Mahindra","category":"SUV","transmission":"Manual","fuel":"Diesel","seats":7,"mileage":15.4,"rate":2808,"rate6h":1130,"rate12h":1690,"extraKmCharge":10,"engineCc":2184,"bootLitres":460,"deposit":6000,"plate":"DL 9C RC 3329","hub":"t3","colorHex":"#2c3e50","terrain":["Highway","Hills","Off-road"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/mahindra-scorpio-classic.jpg","features":["7 seats","132 PS mHawk diesel","Built tough","Great for hill trips"],"reviews":[]}'::jsonb),
  ('dd-mg-astor', '{"name":"MG Astor","brand":"MG","category":"SUV","transmission":"Automatic","fuel":"Petrol","seats":5,"mileage":15.4,"rate":2999,"rate6h":1200,"rate12h":1800,"extraKmCharge":10,"engineCc":1498,"bootLitres":488,"deposit":6000,"plate":"DL 1C SF 3466","hub":"cyber","colorHex":"#7f8c8d","terrain":["City","Highway"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/mg-astor.jpg","features":["ADAS Level 2","Automatic","Panoramic sunroof","Premium cabin"],"reviews":[]}'::jsonb),
  ('dd-hyundai-creta', '{"name":"Hyundai Creta","brand":"Hyundai","category":"SUV","transmission":"Manual","fuel":"Petrol","seats":5,"mileage":17.4,"rate":2999,"rate6h":1200,"rate12h":1800,"extraKmCharge":10,"engineCc":1497,"bootLitres":433,"deposit":6000,"plate":"DL 2C TI 3603","hub":"noida18","colorHex":"#7f8c8d","terrain":["City","Highway","Hills"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/hyundai-creta.jpg","features":["Panoramic sunroof","Ventilated seats","Bose audio","Indias favourite SUV"],"reviews":[]}'::jsonb),
  ('dd-mahindra-thar', '{"name":"Mahindra Thar","brand":"Mahindra","category":"SUV","transmission":"Manual","fuel":"Diesel","seats":5,"mileage":15.2,"rate":3499,"rate6h":1400,"rate12h":2100,"extraKmCharge":10,"engineCc":2184,"bootLitres":150,"deposit":6000,"plate":"DL 3C UL 3740","hub":"cp","colorHex":"#d35400","terrain":["Off-road","Hills"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/mahindra-thar.jpg","features":["4x4 capability","Removable roof","Legendary off-roader","Head-turner"],"reviews":[]}'::jsonb),
  ('dd-mg-hector', '{"name":"MG Hector","brand":"MG","category":"Luxury","transmission":"Automatic","fuel":"Petrol","seats":5,"mileage":13.9,"rate":4299,"rate6h":1720,"rate12h":2580,"extraKmCharge":10,"engineCc":1451,"bootLitres":587,"deposit":15000,"plate":"DL 4C VO 3877","hub":"t3","colorHex":"#ecf0f1","terrain":["Highway","Hills"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/mg-hector.jpg","features":["Panoramic sunroof","587 L boot","Automatic","Huge cabin space"],"reviews":[]}'::jsonb),
  ('dd-mercedes-benz-cla-200', '{"name":"Mercedes Benz CLA 200","brand":"Mercedes-Benz","category":"Luxury","transmission":"Automatic","fuel":"Petrol","seats":5,"mileage":17,"rate":6199,"rate6h":2480,"rate12h":3720,"extraKmCharge":10,"engineCc":1332,"bootLitres":460,"deposit":15000,"plate":"DL 5C WR 4014","hub":"cyber","colorHex":"#1c1c1c","terrain":["City","Highway"],"zeroDep":true,"available":true,"status":"active","rating":4.5,"reviewCount":0,"photo":"cars/mercedes-benz-cla-200.jpg","features":["Mercedes luxury","Ambient lighting","Automatic","Perfect for weddings and shoots"],"reviews":[]}'::jsonb)
on conflict (id) do update set data = excluded.data;

-- Promo codes (WELCOME10 replaces FIRST500 to match the old site).
delete from public.coupons where id = 'cp-first500';
insert into public.coupons (id, data) values
  ('cp-welcome10', '{"code":"WELCOME10","label":"First ride offer","type":"percent","value":10,"minOrder":0,"maxDiscount":1000,"validFrom":"","validTo":"","active":true,"description":"10% off your first ride with DelhiDrive."}'::jsonb),
  ('cp-weekend20', '{"code":"WEEKEND20","label":"Weekend escape","type":"percent","value":20,"minOrder":3000,"maxDiscount":2000,"validFrom":"","validTo":"","active":true,"description":"20% off Friday-Sunday pickups, capped at Rs 2,000."}'::jsonb),
  ('cp-delhi10', '{"code":"DELHI10","label":"Delhi NCR resident","type":"percent","value":10,"minOrder":1500,"maxDiscount":1200,"validFrom":"","validTo":"","active":true,"description":"10% off every rental for NCR residents."}'::jsonb)
on conflict (id) do update set data = excluded.data;

-- Check:
--   select data->>'name' as car, data->>'rate' as per_day from public.fleet order by (data->>'rate')::int;
